<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laporan Medis - <?= $data['nama_lengkap']; ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">

    <style>
        /* RESET & BASE FONT */
        body {
            background-color: #525659;
            font-family: 'Times New Roman', Times, serif;
            font-size: 11pt;
            /* Ukuran font standar surat */
        }

        /* SETTING KERTAS A4 */
        .page {
            width: 210mm;
            min-height: 297mm;
            padding: 15mm 20mm;
            /* Padding Atas/Bawah 15mm, Kiri/Kanan 20mm */
            margin: 20px auto;
            background: white;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
            position: relative;
            box-sizing: border-box;
        }

        /* COMPACT STYLING */
        h3 {
            font-size: 18pt;
            margin-bottom: 2px;
        }

        h4 {
            font-size: 14pt;
            margin-bottom: 10px;
        }

        h6 {
            font-size: 11pt;
            margin-bottom: 5px;
            text-decoration: underline;
            font-weight: bold;
        }

        p,
        td,
        th {
            font-size: 11pt;
        }

        .small-text {
            font-size: 9pt;
        }

        /* GARIS Header */
        .header-line {
            border-bottom: 3px double #000;
            margin-bottom: 15px;
        }

        /* TABLE COMPACT */
        .table-custom td {
            padding: 2px 4px !important;
            border: none;
        }

        .table-score th,
        .table-score td {
            padding: 4px 8px !important;
        }

        /* KOTAK NILAI */
        .box-nilai {
            border: 2px solid #000;
            padding: 10px;
            background-color: #f8f9fa;
            margin-bottom: 15px;
        }

        /* KOTAK FEEDBACK */
        .box-feedback {
            border: 1px solid #000;
            padding: 10px;
            min-height: 100px;
            /* Dikurangi tingginya */
            height: auto;
            background-color: #fff;
            margin-bottom: 10px;
        }

        /* TOMBOL FLOATING */
        .floating-action {
            position: fixed;
            top: 20px;
            right: 20px;
            z-index: 1000;
            background: white;
            padding: 10px;
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
            display: flex;
            gap: 10px;
        }

        /* MEDIA PRINT */
        @media print {
            body {
                background: white;
                margin: 0;
                padding: 0;
            }

            .page {
                width: 100%;
                margin: 0;
                padding: 10mm 15mm;
                box-shadow: none;
                border: none;
            }

            .floating-action,
            .no-print {
                display: none !important;
            }

            /* Paksa muat 1 halaman */
            .page {
                height: 100vh;
                overflow: hidden;
                page-break-after: avoid;
            }
        }
    </style>
</head>

<body>

    <div class="floating-action no-print">
        <a href="<?= BASEURL; ?>/pasien" class="btn btn-sm btn-secondary"><i class="bi bi-arrow-left"></i> Dashboard</a>
        <button onclick="window.print()" class="btn btn-sm btn-primary"><i class="bi bi-printer-fill"></i> Cetak</button>
    </div>

    <div class="page">

        <div class="text-center">
            <h3 class="fw-bold">KOLOCHECK MEDICAL SYSTEM</h3>
            <p class="mb-0 small-text">Sistem Skrining Risiko Penyakit Tidak Menular (PTM)</p>
            <p class="mb-2 small-text">Laporan generated by system | www.kolocheck.id</p>
            <div class="header-line"></div>
        </div>

        <div class="text-center mb-3">
            <h4 class="fw-bold text-uppercase">HASIL SKRINING RISIKO KOLESTEROL</h4>
        </div>

        <table class="table table-sm w-100 mb-3 table-custom">
            <tr>
                <td width="18%">Nama Pasien</td>
                <td width="2%">:</td>
                <td width="45%" class="fw-bold"><?= $data['nama_lengkap']; ?></td>

                <td width="18%">Tgl Periksa</td>
                <td width="2%">:</td>
                <td><?= date('d/m/Y', strtotime($data['tanggal_skrining'])); ?></td>
            </tr>
            <tr>
                <td>NIK</td>
                <td>:</td>
                <td><?= $data['nik']; ?></td>

                <td>No. Registrasi</td>
                <td>:</td>
                <td>REQ-<?= str_pad($data['id'], 6, '0', STR_PAD_LEFT); ?></td>
            </tr>
            <tr>
                <td>Usia / Gender</td>
                <td>:</td>
                <td><?= date_diff(date_create($data['tgl_lahir']), date_create('today'))->y; ?> Thn / <?= substr($data['jenis_kelamin'], 0, 1); ?></td>

                <td>Pekerjaan</td>
                <td>:</td>
                <td><?= $data['pekerjaan']; ?></td>
            </tr>
        </table>

        <div class="box-nilai">
            <div class="row align-items-center text-center">
                <div class="col-4 border-end border-dark py-1">
                    <span class="d-block text-uppercase small-text text-muted">Total Skor</span>
                    <span class="display-4 fw-bold"><?= $data['total_skor']; ?></span>
                    <span class="d-block small-text">/ 100 Poin</span>
                </div>
                <div class="col-8">
                    <span class="text-uppercase small-text text-muted">Kategori Risiko:</span>
                    <h3 class="fw-bold text-uppercase mb-1 mt-1 text-decoration-underline"><?= $data['kategori_risiko']; ?></h3>
                    <?php
                    $saran = "Risiko Rendah. Pertahankan gaya hidup sehat.";
                    if ($data['kategori_risiko'] == 'Sedang') $saran = "Waspada. Perbaiki pola makan & rutin olahraga.";
                    if ($data['kategori_risiko'] == 'Tinggi') $saran = "Bahaya. Segera konsultasikan ke Dokter Spesialis.";
                    ?>
                    <p class="mb-0 fst-italic">"<?= $saran; ?>"</p>
                </div>
            </div>
        </div>

        <h6 class="text-uppercase">I. Rincian Penilaian</h6>
        <table class="table table-bordered border-dark table-sm mb-3 table-score text-center" style="font-size: 10pt;">
            <thead class="table-light border-dark">
                <tr>
                    <th class="text-start">Parameter</th>
                    <th>Skor Anda</th>
                    <th>Nilai Rujukan</th>
                    <th>Interpretasi</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="text-start ps-3">A. Pengetahuan</td>
                    <td><?= $data['skor_pengetahuan']; ?> / 40</td>
                    <td>> 30 (Baik)</td>
                    <td><?= ($data['skor_pengetahuan'] >= 30) ? 'Baik' : 'Kurang'; ?></td>
                </tr>
                <tr>
                    <td class="text-start ps-3">B. Perilaku & Gaya Hidup</td>
                    <td><?= $data['skor_perilaku']; ?> / 20</td>
                    <td>> 14 (Sehat)</td>
                    <td><?= ($data['skor_perilaku'] >= 14) ? 'Sehat' : 'Berisiko'; ?></td>
                </tr>
                <tr>
                    <td class="text-start ps-3">C. Sikap Pencegahan</td>
                    <td><?= $data['skor_sikap']; ?> / 40</td>
                    <td>> 30 (Positif)</td>
                    <td><?= ($data['skor_sikap'] >= 30) ? 'Positif' : 'Negatif'; ?></td>
                </tr>
            </tbody>
        </table>

        <h6 class="text-uppercase">II. Catatan & Rekomendasi Dokter</h6>
        <div class="box-feedback position-relative">
            <?php if ($data['feedback_admin']): ?>
                <p class="mb-0" style="white-space: pre-line; line-height: 1.4;"><?= $data['feedback_admin']; ?></p>
            <?php else: ?>
                <p class="text-muted text-center py-4 mb-0">-- Belum ada catatan spesifik dari dokter. --</p>
            <?php endif; ?>
        </div>

        <?php if ($data['feedback_admin']): ?>
            <div class="text-end mb-4">
                <p class="mb-0 small-text">Diverifikasi oleh Admin Medis</p>
                <p class="mb-0 small-text fw-bold">Tgl: <?= date('d/m/Y H:i', strtotime($data['tanggal_feedback'])); ?></p>
            </div>
        <?php else: ?>
            <div class="mb-4"></div>
        <?php endif; ?>

        <div class="row mt-auto">
            <div class="col-7">
                <p class="small-text text-muted fst-italic mb-1">
                    Catatan:<br>
                    * Dokumen ini sah dan diterbitkan elektronik.<br>
                    * Bawa hasil ini saat konsultasi medis lanjutan.
                </p>
            </div>
            <div class="col-5 text-center">
                <p class="mb-4">Makassar, <?= date('d F Y'); ?></p>
                <br>
                <br>
                <br>
                <p class="fw-bold text-decoration-underline">( Petugas Pemeriksa )</p>
            </div>
        </div>

    </div>
</body>

</html>